spring.profiles.active: local

server.port: 8080

---
spring:
  profiles: local


#Connection
spring.datasource:
  url: jdbc:mysql://localhost:3306/retreat
  username: retreat
  password: retreat
  driver-class-name: com.mysql.jdbc.Driver
  testOnBorrow: true
  validationQuery: SELECT 1

spring.jpa:
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy #org.hibernate.cfg.DefaultNamingStrategy
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect    
    show-sql: false
    properties.hibernate.format_sql: false

logging:
  file: logs/application.log
  level:
    org.thymeleaf: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG    
    org.jejadle.retreat.core: DEBUG
    

spring.thymeleaf:
    cache: false

spring.template.cache: false

---
spring:
  profiles: dev

#Connection
spring.datasource:
  url: jdbc:mysql://localhost:3306/retreat_db  
  username: retreat
  password: jejadle
  driver-class-name: com.mysql.jdbc.Driver
  testOnBorrow: true
  validationQuery: SELECT 1

spring.jpa:
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy #org.hibernate.cfg.DefaultNamingStrategy
    hibernate.ddl-auto: validate
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect    
    show-sql: true

logging:
  file: /var/log/pas_application.log    


spring.thymeleaf:
    cache: false


---
spring:
  profiles: real

#Connection
spring.datasource:
  url: jdbc:h2:mem:test #변경필요
  username: sa
  password:
  driver-class-name: org.h2.Driver #org.mariadb.jdbc.Driver

spring.jpa:
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect #org.hibernate.dialect.MySQL5InnoDBDialect
